docs/index.html

```        <li>Writes code that others can read</li>
<li>Is a team player that goes to the same meetings their co-workers are required to go to</li>```

Added two list items

---

docs/index.html

*Mentorship*: received, and given.
*Code review*: that is thorough, and seeks the best for the contributor and the project.
*Learns from others*: because obviously, that's how it works.
---
Thanks, @bnb!

More community traits

---

docs/index.html

This pull request adds two list items to the index page.
* Updates the docs.
* Asks for help when they need it.

adding qualities about docs and help

---

docs/index.html

I thought it might generate even more social interest if it were easy to tweet about the site. Suggestions welcome on the exact copy for the button and the default tweet text!
<hr>

Add tweet button

---

docs/index.html

Discussions are at the foundation of any team, a 1x engineer will always want to have productive discussions with the team before making a decision that affects the overall process, code base or anything related to what the team is doing.
E.g.: More OOP or more FP? How are we addressing versioning? How are we integrating with what other teams are doing? How are we discussing with other teams, if at all? Do we really need to use library/framework X just because it is new or suits our immediate needs? Why aren't we closing most stories by the end of the spring? Why are we rushing them at the end of the spring? Is Scrum really the best pick for what we're doing, what are the alternatives? How are we deploying our application and how do we communicate this to our users?

Added Productive Discussions Trait

---

docs/index.html

This updates
- twitter:description, removing "1" from the `content
- adds a `.` to one of the items on the list 
:wave:

Updated  twitter:description, Updated list

---

docs/index.html

1x engineers _provide_ tactful, constructive code reviews as well as receiving them

Add trait around providing code reviews

---

docs/index.html

* add docype
* remove `1` from description
* add missing periods from some list items

minor updates

---

docs/index.html

add bulletpoint to 1x.engineer

---

docs/index.html

christina updates

---

docs/index.html

In other parts of the document, we are using serial commas. Examples:
https://github.com/cutenode/1x.engineer/blob/master/docs/index.html#L44
https://github.com/cutenode/1x.engineer/blob/master/docs/index.html#L31
We should be consistent and use them everywhere they are appropriate.

Consistent usage of serial commas

---

docs/index.html

I went quite far into fixing this typo, thought I was being helpful, you know, being a 1x developer and all, but then thought to do some checking existing PRs and issues, and eventually found that it was intentional. So I figured this might help other people wanting to do a good thing :)

Nearly fixed the emdash, instead hint to others

---

docs/index.html

1X engineer can have a colorful desktop background

Add desktop background trait

---

docs/index.html

Says, "I've never heard of that" in lieu of nodding and pretending.

The 1x engineer is willing to say I don't know

---

docs/index.html
docs/scripts/styleswitcher.js
docs/styles/fancystyles.css

Just a quick style update for a cleaner look on mobile devices.

Style update.

---

docs/index.html

Something that stuck with me from [this awesome talk](https://www.youtube.com/watch?v=7-C0KGA7xb4) at JSConfEU.

Add trait about comparing frameworks

---

docs/index.html

There were a couple that just read differently, here are some minor adjustments :)

Minor Updates for Consistent Reading

---

docs/index.html

Sometimes people think that programmer should be using macbook or another high-end PC/laptop. It's totally Wrong!!!! I can code even just using my 2000's old machine :D

Add  new 1x.engineer list: Can code even using old machine

---

docs/index.html

Participates in post-mortem meetings, avoids finger-pointing, and provides constructive criticism.

New trait: "Post-mortem Meetings"

---

docs/index.html

I think it's important to link back to / cite answers you borrow from SO (for provenance, etc) and have added that to your list to encourage others to do so.

Clarify SO bullet

---

docs/index.html

I really hate those. The idea that you're supposed to get riled up about some quirky feature of some programming language, or believe that scheme/lisp is the one true way to program or all of that shit.

Programming language wars

---

docs/index.html

New list entry: Can have a laptop without stickers all over the cover

feat: laptop without stickers

---

docs/index.html

fix: less prescriptive on how to search the internet

---

docs/index.html

Added a trait
Since a 1x engineer is a constant learner, there are many things to learn and a 1x engineer likes to keep a list of them, even though there is so much!

feat: list of things to learn

---

docs/index.html

Add trait: StackOverflow score of like 57

---

docs/index.html

* Reminds about the poor memory of 1x Engineers and they often consult docs logs and debuggers.
* Regular Timing to work sleep and play.
* Meetings and collaboration with people.

feat:  More quirks that 1x Engineers have.

---

docs/index.html

Adds a line about writing tests

---

docs/styles/fancystyles.css

Disables font-smoothing on the body in Fancy.

---

docs/index.html

it also looks better for consistency with the same term used in the next bullet

fix: use "wherever" over less common form

---

docs/index.html

Adds a new point, relevant from discourse from today.

feat: add point about ridiculing entire professions

---

docs/index.html

forgot to change the target branch to main int he original pr

feat: add point about ridiculing entire professions (#151)

---

README.md

Remove link to 10x.engineer

---

docs/index.html

They are willing to do so because they are team players 
Let me know if this can rephrased or any feedback is welcome.

feat: 1x.engineers are not willing to let others fall behind while they progress

---

docs/index.html

I was thinking if this is also another trait of being 1x engineer (I'm proud to be one) 😃

docs: Added unfinished personal projects

---

docs/index.html

Explain what "VC" stands for less ambiguous documentation.

feat: Explain  acronymns where applicable.
